version: "3.9"

services:
  backend:
    build: ./backend
    container_name: quantum-backend
    ports:
      - "8000:8000"
    networks:
      - quantum-net

  frontend:
    build: ./frontend
    container_name: quantum-frontend
    ports:
      - "5173:5173"
    networks:
      - quantum-net
    depends_on:
      - backend

networks:
  quantum-net:
    driver: bridge
